[package]
name = "eigen-client-kms"

version.workspace = true

[dependencies]
aws-config = "1.5.3"
aws-sdk-kms = "1.32.1"
asn1 = "0.16.2"
k256 = "0.13.3"
tokio = { version = "1.38.0", features = ["full"] }